import React from 'react';
import {
  GitMerge,
  Scissors,
  Layers,
  RotateCw,
  Copy,
  Trash2,
  Binary,
  Minimize2,
  Wrench,
  ShieldCheck,
  FileCheck,
  FileImage,
  Image,
  FileText,
  Code,
  Globe,
  Edit3,
  Highlighter,
  PenTool,
  Type,
  Crop,
  Stamp,
  Lock,
  Unlock,
  EyeOff,
  PenLine,
  FileSpreadsheet,
  Search,
  ScanText,
  FileSearch,
  GitCompare,
} from 'lucide-react';
import { ToolItem } from '../../types/pdf';

export interface ToolDefinition extends ToolItem {
  icon: React.ReactNode;
}

export const ALL_TOOLS: ToolDefinition[] = [
  // --- Organize PDF ---
  {
    id: 'merge-pdf',
    name: 'Merge PDF',
    category: 'organize',
    description: 'Combine multiple PDF files into one document in the exact order you choose.',
    badge: 'Popular',
    status: 'READY',
    processingLocation: 'local',
    viewKey: 'merge',
    actionKey: 'merge',
    icon: <GitMerge className="w-8 h-8" />,
  },
  {
    id: 'split-pdf',
    name: 'Split PDF',
    category: 'organize',
    description: 'Separate one or more pages into independent documents with custom page ranges.',
    badge: 'Popular',
    status: 'READY',
    processingLocation: 'local',
    viewKey: 'split',
    actionKey: 'split',
    icon: <Scissors className="w-8 h-8" />,
  },
  {
    id: 'organize-pdf',
    name: 'Organize PDF',
    category: 'organize',
    description: 'Sort, reorder, rotate, delete, or duplicate pages with immediate visual feedback.',
    badge: 'Essential',
    status: 'READY',
    processingLocation: 'local',
    viewKey: 'organize',
    actionKey: 'organize',
    icon: <Layers className="w-8 h-8" />,
  },
  {
    id: 'rotate-pdf',
    name: 'Rotate PDF',
    category: 'organize',
    description: 'Rotate individual pages or entire documents 90° clockwise or counterclockwise.',
    status: 'READY',
    processingLocation: 'local',
    viewKey: 'organize',
    actionKey: 'organize',
    icon: <RotateCw className="w-8 h-8" />,
  },
  {
    id: 'extract-pages',
    name: 'Extract Pages',
    category: 'organize',
    description: 'Pull specific pages or chapters out of your PDF into a brand new document.',
    status: 'READY',
    processingLocation: 'local',
    viewKey: 'split',
    actionKey: 'split',
    icon: <Scissors className="w-8 h-8" />,
  },
  {
    id: 'delete-pages',
    name: 'Delete Pages',
    category: 'organize',
    description: 'Remove unwanted or blank pages cleanly while preserving the rest of your file.',
    status: 'READY',
    processingLocation: 'local',
    viewKey: 'organize',
    actionKey: 'organize',
    icon: <Trash2 className="w-8 h-8" />,
  },
  {
    id: 'duplicate-pages',
    name: 'Duplicate Pages',
    category: 'organize',
    description: 'Clone any page instantly to create copies or repeating section templates.',
    status: 'READY',
    processingLocation: 'local',
    viewKey: 'organize',
    actionKey: 'organize',
    icon: <Copy className="w-8 h-8" />,
  },
  {
    id: 'page-numbers',
    name: 'Page Numbers',
    category: 'organize',
    description: 'Insert clear page numbering headers and footers with custom positions.',
    status: 'COMING_SOON',
    processingLocation: 'local',
    icon: <Binary className="w-8 h-8" />,
  },

  // --- Optimize PDF ---
  {
    id: 'compress-pdf',
    name: 'Compress PDF',
    category: 'optimize',
    description: 'Upcoming local optimization to reduce PDF file size while preserving high visual quality.',
    badge: 'Roadmap',
    status: 'COMING_SOON',
    processingLocation: 'local',
    viewKey: 'compress',
    icon: <Minimize2 className="w-8 h-8" />,
  },
  {
    id: 'repair-pdf',
    name: 'Repair PDF',
    category: 'optimize',
    description: 'Recover data and fix broken xref tables from damaged or corrupted PDFs.',
    status: 'COMING_SOON',
    processingLocation: 'local',
    icon: <Wrench className="w-8 h-8" />,
  },
  {
    id: 'remove-metadata',
    name: 'Remove Metadata',
    category: 'optimize',
    description: 'Strip hidden author info, creation timestamps, and revision histories.',
    status: 'COMING_SOON',
    processingLocation: 'local',
    icon: <ShieldCheck className="w-8 h-8" />,
  },
  {
    id: 'pdf-to-pdfa',
    name: 'PDF → PDF/A',
    category: 'optimize',
    description: 'Convert standard documents to ISO-compliant archival formats for legal records.',
    status: 'COMING_SOON',
    processingLocation: 'local',
    icon: <FileCheck className="w-8 h-8" />,
  },

  // --- Convert PDF ---
  {
    id: 'pdf-to-jpg',
    name: 'PDF → JPG',
    category: 'convert',
    description: 'Render pages as individual high-resolution JPG images directly in browser.',
    status: 'COMING_SOON',
    processingLocation: 'local',
    viewKey: 'convert',
    icon: <FileImage className="w-8 h-8" />,
  },
  {
    id: 'pdf-to-png',
    name: 'PDF → PNG',
    category: 'convert',
    description: 'Render PDF pages into crisp raster PNG image files in your browser.',
    status: 'COMING_SOON',
    processingLocation: 'local',
    viewKey: 'convert',
    icon: <FileImage className="w-8 h-8" />,
  },
  {
    id: 'jpg-to-pdf',
    name: 'JPG → PDF',
    category: 'convert',
    description: 'Assemble JPG photographs and graphic designs into a neat PDF portfolio.',
    status: 'COMING_SOON',
    processingLocation: 'local',
    viewKey: 'convert',
    icon: <Image className="w-8 h-8" />,
  },
  {
    id: 'png-to-pdf',
    name: 'PNG → PDF',
    category: 'convert',
    description: 'Turn PNG image files into wrapped, standardized PDF pages.',
    status: 'COMING_SOON',
    processingLocation: 'local',
    viewKey: 'convert',
    icon: <Image className="w-8 h-8" />,
  },
  {
    id: 'pdf-to-text',
    name: 'PDF → Text',
    category: 'convert',
    description: 'Extract raw text content into standard plain text (.txt) files.',
    status: 'COMING_SOON',
    processingLocation: 'local',
    icon: <FileText className="w-8 h-8" />,
  },
  {
    id: 'pdf-to-markdown',
    name: 'PDF → Markdown',
    category: 'convert',
    description: 'Convert structured document paragraphs and headings into clean Markdown.',
    status: 'COMING_SOON',
    processingLocation: 'local',
    icon: <Code className="w-8 h-8" />,
  },
  {
    id: 'html-to-pdf',
    name: 'HTML → PDF',
    category: 'convert',
    description: 'Render web articles, styling, and HTML templates into print-ready PDFs.',
    status: 'COMING_SOON',
    processingLocation: 'local',
    icon: <Globe className="w-8 h-8" />,
  },

  // --- Edit PDF ---
  {
    id: 'edit-pdf',
    name: 'Edit PDF',
    category: 'edit',
    description: 'Add and format text, draw shapes, and place custom imagery onto pages.',
    status: 'COMING_SOON',
    processingLocation: 'local',
    icon: <Edit3 className="w-8 h-8" />,
  },
  {
    id: 'annotate-pdf',
    name: 'Annotate PDF',
    category: 'edit',
    description: 'Add freehand sketches, margin comments, and sticky note callouts.',
    status: 'COMING_SOON',
    processingLocation: 'local',
    icon: <PenTool className="w-8 h-8" />,
  },
  {
    id: 'highlight-pdf',
    name: 'Highlight',
    category: 'edit',
    description: 'Apply semi-transparent colored highlights across key phrases and citations.',
    status: 'COMING_SOON',
    processingLocation: 'local',
    icon: <Highlighter className="w-8 h-8" />,
  },
  {
    id: 'add-text',
    name: 'Add Text',
    category: 'edit',
    description: 'Type new text blocks, titles, and disclaimers anywhere on your document.',
    status: 'COMING_SOON',
    processingLocation: 'local',
    icon: <Type className="w-8 h-8" />,
  },
  {
    id: 'crop-pdf',
    name: 'Crop PDF',
    category: 'edit',
    description: 'Trim page margins and unwanted scanner borders with custom crop boxes.',
    status: 'COMING_SOON',
    processingLocation: 'local',
    icon: <Crop className="w-8 h-8" />,
  },
  {
    id: 'watermark-pdf',
    name: 'Watermark',
    category: 'edit',
    description: 'Stamp custom confidentiality labels or brand logos across document pages.',
    status: 'COMING_SOON',
    processingLocation: 'local',
    icon: <Stamp className="w-8 h-8" />,
  },

  // --- PDF Security ---
  {
    id: 'protect-pdf',
    name: 'Protect PDF',
    category: 'security',
    description: 'Planned client-side password encryption and document permissions.',
    status: 'COMING_SOON',
    processingLocation: 'local',
    icon: <Lock className="w-8 h-8" />,
  },
  {
    id: 'unlock-pdf',
    name: 'Unlock PDF',
    category: 'security',
    description: 'Remove passwords and permissions from authorized PDFs when password is known.',
    status: 'COMING_SOON',
    processingLocation: 'local',
    icon: <Unlock className="w-8 h-8" />,
  },
  {
    id: 'redact-pdf',
    name: 'Redact PDF',
    category: 'security',
    description: 'Permanently remove sensitive text and graphics from the underlying PDF stream.',
    status: 'COMING_SOON',
    processingLocation: 'local',
    icon: <EyeOff className="w-8 h-8" />,
  },
  {
    id: 'sign-pdf',
    name: 'Sign PDF',
    category: 'security',
    description: 'Draw or insert an electronic signature image onto agreements and forms.',
    status: 'COMING_SOON',
    processingLocation: 'local',
    icon: <PenLine className="w-8 h-8" />,
  },
  {
    id: 'flatten-pdf',
    name: 'Flatten PDF',
    category: 'security',
    description: 'Lock form fields and annotations into static non-editable page graphics.',
    status: 'COMING_SOON',
    processingLocation: 'local',
    icon: <FileSpreadsheet className="w-8 h-8" />,
  },

  // --- PDF Intelligence ---
  {
    id: 'viewer-search',
    name: 'Viewer & Search',
    category: 'intelligence',
    description: 'High-fidelity canvas viewer with zoom controls, thumbnails, and real-time search.',
    badge: 'Interactive',
    status: 'READY',
    processingLocation: 'local',
    viewKey: 'viewer',
    actionKey: 'view',
    icon: <Search className="w-8 h-8" />,
  },
  {
    id: 'ocr-pdf',
    name: 'OCR PDF',
    category: 'intelligence',
    description: 'Planned in-browser OCR to convert scanned image pages into selectable text.',
    status: 'COMING_SOON',
    processingLocation: 'local',
    icon: <ScanText className="w-8 h-8" />,
  },
  {
    id: 'searchable-pdf',
    name: 'Searchable PDF',
    category: 'intelligence',
    description: 'Embed hidden OCR text layers beneath scanned page images.',
    status: 'COMING_SOON',
    processingLocation: 'local',
    icon: <FileSearch className="w-8 h-8" />,
  },
  {
    id: 'compare-pdf',
    name: 'Compare PDF',
    category: 'intelligence',
    description: 'Spot visual and typographical differences between two versions of a document.',
    status: 'COMING_SOON',
    processingLocation: 'local',
    icon: <GitCompare className="w-8 h-8" />,
  },
];
